# Generated by Django 4.2.16 on 2026-08-11 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('parsed_data', models.JSONField(blank=True, default=dict)),
                ('is_parsed', models.BooleanField(default=False)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Resume',
                'verbose_name_plural': 'Resumes',
                'db_table': 'resumes_resume',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='TargetRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('software_engineering', 'Software Engineering'), ('data_science', 'Data Science'), ('machine_learning', 'Machine Learning'), ('devops', 'DevOps / Cloud'), ('frontend', 'Frontend Development'), ('backend', 'Backend Development'), ('fullstack', 'Full Stack Development'), ('mobile', 'Mobile Development'), ('cybersecurity', 'Cybersecurity'), ('product_management', 'Product Management'), ('other', 'Other')], default='other', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_roles_list', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Target Role',
                'verbose_name_plural': 'Target Roles',
                'db_table': 'resumes_target_role',
                'ordering': ['-is_primary', 'role_name'],
                'indexes': [models.Index(fields=['student', 'is_primary'], name='resumes_tar_student_8eb44e_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='targetrole',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('student',), name='unique_primary_target_role_per_student'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['student', 'is_active'], name='resumes_res_student_a9d26c_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['student', 'version'], name='resumes_res_student_3ac64c_idx'),
        ),
    ]
