# Generated by Django 4.2.16 on 2026-08-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='parse_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='parse_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['student', 'parse_status'], name='resumes_res_student_a47ca8_idx'),
        ),
    ]
