# Generated by Django 4.2.16 on 2026-08-11 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreparationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preparation_days', models.IntegerField(default=30)),
                ('topic_weights', models.JSONField(blank=True, default=dict)),
                ('recommended_sequence', models.JSONField(blank=True, default=list)),
                ('qaoa_energy', models.FloatField(blank=True, null=True)),
                ('circuit_depth', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_plans', to='accounts.studentprofile')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preparation_plans', to='resumes.targetrole')),
            ],
            options={
                'verbose_name': 'Preparation Plan',
                'verbose_name_plural': 'Preparation Plans',
                'db_table': 'preparation_plan',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PracticeModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=255)),
                ('sub_topics', models.JSONField(blank=True, default=list)),
                ('scheduled_day', models.PositiveIntegerField()),
                ('estimated_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resources', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_modules', to='preparation.preparationplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_modules', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Practice Module',
                'verbose_name_plural': 'Practice Modules',
                'db_table': 'preparation_practice_module',
                'ordering': ['scheduled_day', 'topic'],
            },
        ),
        migrations.AddIndex(
            model_name='preparationplan',
            index=models.Index(fields=['student', 'is_active'], name='preparation_student_7f2b59_idx'),
        ),
        migrations.AddIndex(
            model_name='preparationplan',
            index=models.Index(fields=['student', 'generated_at'], name='preparation_student_6d613b_idx'),
        ),
        migrations.AddIndex(
            model_name='practicemodule',
            index=models.Index(fields=['plan', 'scheduled_day'], name='preparation_plan_id_6939d6_idx'),
        ),
        migrations.AddIndex(
            model_name='practicemodule',
            index=models.Index(fields=['student', 'status'], name='preparation_student_d919c1_idx'),
        ),
    ]
