# Generated by Django 4.2.16 on 2026-08-11 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0001_initial'),
        ('accounts', '0001_initial'),
        ('preparation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_type', models.CharField(choices=[('technical', 'Technical'), ('hr', 'HR'), ('project', 'Project-Based'), ('coding', 'Coding'), ('mixed', 'Mixed (All Rounds)')], default='mixed', max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed'), ('aborted', 'Aborted')], default='created', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantum_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='preparation.preparationplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.studentprofile')),
                ('target_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='resumes.targetrole')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'db_table': 'sessions_interview_session',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('turn_number', models.PositiveIntegerField()),
                ('phase', models.CharField(choices=[('warmup', 'Warm-Up'), ('technical', 'Technical'), ('coding', 'Coding'), ('hr', 'HR / Behavioural'), ('project', 'Project-Based'), ('closing', 'Closing')], default='technical', max_length=20)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('conceptual', 'Conceptual'), ('behavioral', 'Behavioural (STAR)'), ('coding', 'Coding Problem'), ('project', 'Project Discussion'), ('situational', 'Situational')], default='conceptual', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('expected_concepts', models.JSONField(blank=True, default=list)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'db_table': 'sessions_interview_question',
                'ordering': ['turn_number'],
            },
        ),
        migrations.CreateModel(
            name='StudentResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='responses/audio/%Y/%m/')),
                ('response_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('concepts_covered', models.JSONField(blank=True, default=list)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('ai_feedback', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='interview_sessions.interviewquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Student Response',
                'verbose_name_plural': 'Student Responses',
                'db_table': 'sessions_student_response',
                'ordering': ['question__turn_number'],
                'indexes': [models.Index(fields=['session'], name='sessions_st_session_71fa5c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['student', 'status'], name='sessions_in_student_c1fcde_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['student', 'created_at'], name='sessions_in_student_3d1e1a_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'turn_number'], name='sessions_in_session_76750a_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'phase'], name='sessions_in_session_69413e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='interviewquestion',
            unique_together={('session', 'turn_number')},
        ),
    ]
