# Generated by Django 4.2.16 on 2026-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='follow_up_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
