# Generated by Django 4.2.16 on 2026-08-11 15:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('interview_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('technical_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('communication_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('behavioural_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('coding_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('problem_solving_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('strengths', models.JSONField(default=list)),
                ('improvement_areas', models.JSONField(default=list)),
                ('detailed_feedback', models.JSONField(default=dict)),
                ('speech_metrics', models.JSONField(default=dict)),
                ('behavioural_metrics', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assessment', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments_assessment',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillGap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('language', 'Programming Language'), ('framework', 'Framework / Library'), ('concept', 'CS Concept'), ('tool', 'Tool / Platform'), ('soft_skill', 'Soft Skill')], default='concept', max_length=20)),
                ('current_level', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('target_level', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('gap_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('identified_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_gaps', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_gaps', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Skill Gap',
                'verbose_name_plural': 'Skill Gaps',
                'db_table': 'assessments_skill_gap',
                'ordering': ['-gap_score', 'skill_name'],
                'indexes': [models.Index(fields=['student', 'priority'], name='assessments_student_5a098c_idx'), models.Index(fields=['student', 'resolved_at'], name='assessments_student_916af0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodingSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField()),
                ('language', models.CharField(choices=[('python', 'Python 3'), ('javascript', 'JavaScript (Node.js)'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go')], default='python', max_length=20)),
                ('code', models.TextField()),
                ('execution_output', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('passed_count', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('runtime_ms', models.IntegerField(blank=True, null=True)),
                ('memory_kb', models.IntegerField(blank=True, null=True)),
                ('timed_out', models.BooleanField(default=False)),
                ('correctness_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('efficiency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('overall_score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('llm_review', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_submissions', to='interview_sessions.interviewsession')),
            ],
            options={
                'verbose_name': 'Coding Submission',
                'verbose_name_plural': 'Coding Submissions',
                'db_table': 'assessments_coding_submission',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['session'], name='assessments_session_5315c1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['session'], name='assessments_session_80a7b1_idx'),
        ),
    ]
