# Generated by Django 4.2.16 on 2026-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_codingproblem_codingtestcase_codingsubmission_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codingtestcase',
            options={'ordering': ['problem', 'order'], 'verbose_name': 'Coding Test Case', 'verbose_name_plural': 'Coding Test Cases'},
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='expected_complexity',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='codingproblem',
            name='topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='codingsubmission',
            name='attempt_type',
            field=models.CharField(choices=[('interview', 'Interview Assessment'), ('practice', 'Coding Practice')], default='practice', max_length=10),
        ),
    ]
